### ISSUE TITLE
Add support for IOTA 1.5 API

### ISSUE THREAD

**Issue by CodeMonkeySteve** [vivekmarakana/iota.lib.rb#16]
I've spent most of the day getting version 1.0 of the IOTA Hornet server to run, and now discovered that there's a new API, so my client is no longer compatible (yay).  We'll need to update this gem to support the new API.  

Here's the release announcement:
  https://blog.iota.org/the-new-chrysalis-network-is-live/

And here's the API docs, that's all the information I can find so far:
  https://editor.swagger.io/?url=https://raw.githubusercontent.com/rufsam/protocol-rfcs/master/text/0026-rest-api/rest-api.yaml

**Comment by vivekmarakana** [comment]
I'm currently working on adding support for the new API. Will be released soon.

**Comment by CodeMonkeySteve** [comment]
I hate to pester you, but we have a backlog of ~120,000 IOTA transactions to create (although I guess now they're "messages").  If there's anything I can do to help please let me know, otherwise I'll just shut up and be patient.

**Comment by vivekmarakana** [comment]
I was trying to create a ruby bindings for [iota.rs](https://github.com/iotaledger/iota.rs#bindings) library to make it similar to others, but it proved to be harder on my mac mini due to M1 chip. I'm now trying to do the same using my old macbook. Will keep updating here.

**Comment by CodeMonkeySteve** [comment]
That's a good plan, I was thinking of doing the same with `iota.c` and `ffi`, I don't know if that would be any easier than iota.rs.  Thanks for the update.

**Comment by CodeMonkeySteve** [comment]
On a whim, I wrote a quick-n-dirty Ruby wrapper for API v1.5, with just enough support to create messages and check for confirmation.  It's working well enough for me for now, and thought I'd share what I have in case it's any use to you: https://gist.github.com/CodeMonkeySteve/d7b75da979520bea8142f06d0d4b9f2a .  It's not really worth extracting into its own gem, but it'll do until you add support to the official-unofficial gem.

I found API v1.5 to be much more friendly then v1.0, at least for zero-value transactions.  Also the new server/protocol/network is performing way faster: triple the throughput with less than half of the CPU.  The PoW runs so fast that I suspect the limiting factors now are things like TCP connection time, which I suppose is a nice problem to have.

**Comment by vivekmarakana** [comment]
@CodeMonkeySteve This is great.

Adding ruby binding from rust is taking more time than I expected. I've already added bindings for following apis:
```
// Node APIs
getInfo
getHealth
getPeers
getTips
getOutput
getAddressBalance
getAddressOutputs
getMilestone
getMilestoneUTXOChanges
getReceipts
getReceiptsMigratedAt
getTreasury
getIncludedMessage

// High Level APIs
getAddresses
getBalance
getAddressBalances

// Utilities
generateMnemonic
mnemonicToHexSeed
```

I'll make a release soon as soon as the messaging apis are added and tested.

**Comment by vivekmarakana** [comment]
I've decided to create a separate gem for post chrysalis versions. It will also include iota 2.0 changes. Closing this issue and marking this repo as read only.
