### ISSUE TITLE
thisBalance doesn't exist

### ISSUE THREAD

**Issue by TAiS46** [vivekmarakana/iota.lib.rb#2]
`NameError: undefined local variable or method `thisBalance' for #<IOTA::Models::Account:0x0000556f58c00c48>`

https://github.com/vivekmarakana/iota.lib.rb/blob/a11f31a441dae7ea007c18211e05b2c3fa91d349/lib/iota/models/account.rb#L376

**Comment by vivekmarakana** [comment]
Fixed.
